### ISSUE TITLE
Do not show the status (vacant, full) if you have already attended an activity.

### ISSUE THREAD

**Issue by forfeen** [bleachjade/Kvent#30]
I think the status should be displayed. Even if the user has joined
<img width="425" alt="Screen Shot 2563-11-23 at 01 00 30" src="https://user-images.githubusercontent.com/52417088/99911479-49cbce80-2d27-11eb-8db9-ef0054d068bc.png">

**Comment by bleachjade** [comment]
You already fixed it! Thanks
![image](https://user-images.githubusercontent.com/46812243/102444616-3678fe00-405c-11eb-8388-2ac63ff5815f.png)
