### ISSUE TITLE
Event owners can join theirs event post.

### ISSUE THREAD

**Issue by nicenicegame** [bleachjade/Kvent#31]
I've try to join the event post that I've been created by enter the url `/join/some_event_id` and it redirect me back to home page with the message that I successfully joined my event. After that, I go to check the event detail page that I've been joined, my name was shown in the participants list.

**Comment by nicenicegame** [comment]
<img width="560" alt="Screen Shot 2563-11-29 at 23 31 22" src="https://user-images.githubusercontent.com/59835246/100547800-4abaae00-329b-11eb-9f37-0e8fdc20da73.png">

**Comment by bleachjade** [comment]
@nicenicegame Thank you to point this out! we already fixed it krub

![image](https://user-images.githubusercontent.com/46812243/101871936-04c4ea80-3bb7-11eb-9720-9632827f7dd1.png)
