### ISSUE TITLE
UI : The text container for event descriptions is not word-warp.

### ISSUE THREAD

**Issue by ZEZAY** [bleachjade/Kvent#33]
Like This:

at home page
Url: https://kventeventapplication.herokuapp.com/
![image](https://user-images.githubusercontent.com/44806732/100896381-23f5b500-34f1-11eb-8552-c7505b3e01c8.png)

at event detail
![image](https://user-images.githubusercontent.com/44806732/100896194-f577da00-34f0-11eb-97a7-17a32a41dd59.png)

**Comment by bleachjade** [comment]
@ZEZAY I've fixed it! Thank you krub

![image](https://user-images.githubusercontent.com/46812243/101234891-e2822700-36f5-11eb-8eb6-c4f468d07376.png)

![image](https://user-images.githubusercontent.com/46812243/101234893-e9a93500-36f5-11eb-8891-4460ba7c951d.png)
