### ISSUE TITLE
UI suggestion: link to event detail should be cover the whole event display area 

### ISSUE THREAD

**Issue by ZEZAY** [bleachjade/Kvent#34]
I found that the link to event detail contains only the event title text.
My suggestion is to make the link cover the whole event display area, so it easy for the user to click it.

URL: https://kventeventapplication.herokuapp.com/

![image](https://user-images.githubusercontent.com/44806732/100897450-476d2f80-34f2-11eb-93c8-14f86c6e1625.png)

**Comment by bleachjade** [comment]
@ZEZAY Fixed! Thank you krub

![image](https://user-images.githubusercontent.com/46812243/101234949-8bc91d00-36f6-11eb-827c-f20548f7ce4b.png)
