### ISSUE TITLE
Suggestion: to delete the event

### ISSUE THREAD

**Issue by ZEZAY** [bleachjade/Kvent#35]
I found that when the event host wants to delete the event, he can use just one click on the delete button, and then the event suddenly disappeared.

My suggestion to delete the event, I think you should ask for a double-check to make sure that the host really wants to delete it. It can be a page, or pop-up ask to enter the event title like when you want to delete GitHub repo or just and normal button said 'I'm sure to delete it'.

![image](https://user-images.githubusercontent.com/44806732/100898665-96679480-34f3-11eb-8460-fbd74bffac3e.png)

**Comment by bleachjade** [comment]
@ZEZAY Thank you for your suggestion, I fixed it.

![image](https://user-images.githubusercontent.com/46812243/101239582-1face000-371b-11eb-959c-eb02ffc2a0d6.png)
