### ISSUE TITLE
Create event page: report

### ISSUE THREAD

**Issue by ZEZAY** [bleachjade/Kvent#36]
On the Create event page, I think it has a lot of wried topic.

URL: https://kventeventapplication.herokuapp.com/create/

![image](https://user-images.githubusercontent.com/44806732/100898877-cc0c7d80-34f3-11eb-828c-3e8a6d2dd085.png)

1. If I use the wrong information and the event can't be created, It didn't show any warning. It only not redirect me to the home page.

2. And when the event created, It immediately redirects to the home page with no message.

3. I can create event without any image.

4. I can create event with zero and a negative capacity.

![image](https://user-images.githubusercontent.com/44806732/100900417-691be600-34f5-11eb-924b-fc9528522412.png)

5. I can create event that takes place in the past.

![image](https://user-images.githubusercontent.com/44806732/100900543-8781e180-34f5-11eb-9ddf-4d3ba14505cf.png)

**Comment by bleachjade** [comment]
**Localhost** - we are currently working on this part. We'll deploy very soon!
- [x] If I use the wrong information and the event can't be created, It didn't show any warning. It only not redirect me to the home page.
![image](https://user-images.githubusercontent.com/46812243/102191396-ef6bfb00-3eeb-11eb-8d65-880ec2c6332c.png)

**Heroku**
- [x] when the event created, It immediately redirects to the home page with no message.
![image](https://user-images.githubusercontent.com/46812243/102191491-11657d80-3eec-11eb-8fa9-729f4354b680.png)

- [x] I can create an event without any image.
![image](https://user-images.githubusercontent.com/46812243/102190836-1b3ab100-3eeb-11eb-8951-d506e3edc489.png)

- [x] I can create an event with zero and a negative capacity.
![image](https://user-images.githubusercontent.com/46812243/102190673-e7f82200-3eea-11eb-8fb7-ee843f96d5b4.png)

- [x] I can create an event that takes place in the past.
![image](https://user-images.githubusercontent.com/46812243/102190625-d9aa0600-3eea-11eb-85e6-953e625bfd5d.png)
